version: '3.8'

services:
  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

  backend:
    build:
      context: ./naya-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/nayadb
    depends_on:
      - mongo

  frontend:
    build:
      context: ./naya-web
      dockerfile: Dockerfile.local
    ports:
      - "3000:3000"
    volumes:
      - ./naya-web:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8080

    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  mongodb:
