name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: naya-web
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install
      - run: npm test -- --watchAll=false

  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: naya-api
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install
      - run: npx jest

  deploy:
    needs:
      - test-frontend
      - test-backend
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3



      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
         credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Configure Docker to use Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      # - name: Build & Push Frontend Docker image
      #   run: |
      #     docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/nayaregistry/naya-web:latest ./naya-web
      #     docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/nayaregistry/naya-web:latest

      # - name: Build & Push Backend Docker image
      #   run: |
      #     docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/nayaregistry/naya-api:latest ./naya-api
      #     docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/nayaregistry/naya-api:latest

      
      # - name: Deploy Backend to Cloud Run
      #   uses: google-github-actions/deploy-cloudrun@v2
      #   with:
      #     service: naya-backend
      #     image: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/nayaregistry/naya-api:latest
      #     region: ${{ secrets.GCP_REGION }}
      #     flags: --allow-unauthenticated --region=us-central1
      #     env_vars: |
      #       MONGO_URI=${{ secrets.MONGO_URI }}


      - name: Deploy Frontend to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: naya-frontend
          image: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/nayaregistry/naya-web:latest
          region: us-central1
          flags: --allow-unauthenticated --region=us-central1




      
      # - name: Set up Google Cloud SDK
      #   uses: google-github-actions/setup-gcloud@v2
      #   with:
      #     project_id: ${{ secrets.GCP_PROJECT_ID }}
      #     service_account_key: ${{ secrets.GCP_CREDENTIALS }}
      #     install_components: 'gke-gcloud-auth-plugin'
      #     export_default_credentials: true

     

      # - name: Install Terraform
      #   uses: hashicorp/setup-terraform@v3

      # - name: Terraform Init and Plan
      #   working-directory: terraform
      #   run: |
      #     terraform init


      # - name: Import existing Artifact Registry (if needed)
      #   working-directory: terraform
      #   run: |
      #     terraform import google_artifact_registry_repository.naya_registry projects/${{ secrets.GCP_PROJECT_ID }}/locations/us-central1/repositories/nayaregistry || true
     
      # - name: Terraform Plan & Apply
      #   working-directory: terraform
      #   run: |
      #     terraform plan -var-file="terraform.tfvars" \
      #              -var='credentials_json=${{ secrets.GCP_CREDENTIALS }}'
      #     terraform apply -auto-approve -var-file="terraform.tfvars" \
      #             -var='credentials_json=${{ secrets.GCP_CREDENTIALS }}'

      # - name: Configure Docker to use Artifact Registry
      #   run: |
      #     gcloud auth configure-docker us-central1-docker.pkg.dev

      # - name: Debug Docker Auth Config
      #   run: cat ~/.docker/config.json


      # - name: Build & Push Frontend Docker image
      #   run: |
      #     docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/nayaregistry/naya-web:latest ./naya-web
      #     docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/nayaregistry/naya-web:latest

      # - name: Build & Push Backend Docker image
      #   run: |
      #     docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/nayaregistry/naya-api:latest ./naya-api
      #     docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/nayaregistry/naya-api:latest 

      
      # - name: Terraform Init and Plan
        # run: |
        #   terraform init
        #   terraform plan \
        #     -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
        #     -var="region=${{ secrets.GCP_REGION }}" \
        #     -var="credentials_json=${{ secrets.GCP_CREDENTIALS }}"


      # Optional steps if you want to preview Docker image builds
      # - name: Configure Docker to use gcloud
      #   run: gcloud auth configure-docker asia-south1-docker.pkg.dev

      # - name: Build Frontend Docker image
      #   run: docker build -t frontend-preview ./naya-web

      # - name: Build Backend Docker image
      #   run: docker build -t backend-preview ./naya-api








# name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main

# jobs:
#   test-frontend:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: naya-web
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           node-version: '16'
#       - run: npm install
#       - run: npm test -- --watchAll=false

#   test-backend:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: naya-api
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           node-version: '16'
#       - run: npm install
#       - run: npx jest

#   deploy:
#     needs:
#       - test-frontend
#       - test-backend
#     if: ${{ success() }}
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Google Cloud SDK
#         uses: google-github-actions/setup-gcloud@v1
#         with:
#           project_id: ${{ secrets.GCP_PROJECT_ID }}
#           service_account_key: ${{ secrets.GCP_CREDENTIALS }}
#           export_default_credentials: true

#       - name: Install Terraform
#         uses: hashicorp/setup-terraform@v3

#       - name: Run Terraform to create Artifact Registry
#         working-directory: terraform
#         run: |
#           terraform init
#           terraform plan -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
#                  -var="region=${{ secrets.GCP_REGION }}" \
#                  -var="credentials_json=${{ secrets.GCP_CREDENTIALS }}"
      #     terraform apply -auto-approve -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
      #                                      -var="region=${{ secrets.GCP_REGION }}" \
      #                                      -var="credentials_json=${{ secrets.GCP_CREDENTIALS }}"

      # - name: Configure Docker to use gcloud
      #   run: gcloud auth configure-docker asia-south1-docker.pkg.dev

      # - name: Build & Push Frontend Docker image
      #   run: |
      #     docker build -t asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/nayaregistry/naya-web:latest ./naya-web
      #     docker push asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/nayaregistry/naya-web:latest

      # - name: Build & Push Backend Docker image
      #   run: |
      #     docker build -t asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/nayaregistry/naya-api:latest ./naya-api
      #     docker push asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/nayaregistry/naya-api:latest




  # deploy:
  #   needs:
  #     - test-frontend
  #     - test-backend
  #   if: ${{ success() }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Set up Google Cloud SDK
  #       uses: google-github-actions/setup-gcloud@v1
  #       with:
  #         project_id: ${{ secrets.GCP_PROJECT_ID }}
  #         service_account_key: ${{ secrets.GCP_CREDENTIALS }}
  #         export_default_credentials: true

  #     - name: Configure Docker to use gcloud
  #       run: gcloud auth configure-docker

  #     - name: Build & Push Frontend Docker image
  #       run: |
  #         docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/naya-web ./naya-web
  #         docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/naya-web

  #     - name: Build & Push Backend Docker image
  #       run: |
  #         docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/naya-api ./naya-api
  #         docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/naya-api

  #     # - name: Deploy with Terraform (optional)
  #     #   working-directory: terraform
  #     #   run: |
  #     #     terraform init
  #     #     terraform apply -auto-approve
  #     #   env:
  #     #     GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
  #     #     GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  #     #     GCP_REGION: ${{ secrets.GCP_REGION }}
