name: Deploy to GCP

on:
  workflow_run:
    workflows: ["frontend", "backend"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Configure Docker to use gcloud
        run: |
          gcloud auth configure-docker

      - name: Build & Push Frontend Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/naya-web ./naya-web
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/naya-web

      - name: Build & Push Backend Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/naya-api ./naya-api
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/naya-api

      # - name: Deploy with Terraform
      #   working-directory: terraform
      #   run: |
      #     terraform init
      #     terraform apply -auto-approve
      #   env:
      #     GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      #     GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      #     GCP_REGION: ${{ secrets.GCP_REGION }}
